#! /bin/sh
### BEGIN INIT INFO
# Provides:   gce-heartbeat
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:  gce-heartbeat - Google Compute Engine Heartbeat
# Description:    gce-heartbeat - Google Compute Engine Heartbeat
### END INIT INFO

INTERVAL=
PROJECT=
PRIMARY=
PRIMARY_ZONE=
REGION=
SECONDARY=
SECONDARY_ZONE=
ADDRESS_NAME=
DB=
DB_USER=
DB_PASSWORD=
DB_DIR=

DAEMON="/usr/local/bin/heartbeat.py"
DAEMON_ARGS="--interval $INTERVAL --project $PROJECT --primary $PRIMARY --primary-zone $PRIMARY_ZONE --region $REGION --secondary $SECONDARY --secondary-zone $SECONDARY_ZONE --address-name $ADDRESS_NAME --db $DB --db-user $DB_USER --db-password $DB_PASSWORD --db-dir $DB_DIR"
NAME="gce-heartbeat"
DESC="gce-heartbeat"

RUNDIR="/var/run"
PIDFILE="$RUNDIR/gce-heartbeat.pid"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

set -e

case "$1" in
  start)
  echo -n "Starting $DESC: "
  touch $PIDFILE

  if start-stop-daemon --start --background --quiet --umask 007 --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
  then
    echo "$NAME."
  else
    echo "failed"
  fi
  ;;
  stop)
  echo -n "Stopping $DESC: "
  if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
  then
    echo "$NAME."
  else
    echo "failed"
  fi
  rm -f $PIDFILE
  sleep 1
  ;;

  restart|force-reload)
  ${0} stop
  ${0} start
  ;;

  status)
  echo -n "$DESC is "
  if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
  then
    echo "running"
  else
    echo "not running"
    exit 1
  fi
  ;;

  *)
  echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
  exit 1
  ;;
esac

exit 0
